#!/usr/bin/env python3
"""Create a local Canarytokens.org AWS credential seed overlay."""

from __future__ import annotations

import argparse
import json
import os
import sys
import urllib.error
import urllib.parse
import urllib.request
from pathlib import Path
from typing import Any


DEFAULT_BASE_URL = "https://canarytokens.org"
DEFAULT_ENDPOINT = "/d3aece8093b71007b5ccfedad91ebb11/generate"


def _arg_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description=(
            "Create Canarytokens.org AWS keys and write an ignored local seed "
            "overlay for the DVAP compose stack."
        )
    )
    parser.add_argument("--email", default=os.environ.get("CANARYTOKENS_EMAIL"))
    parser.add_argument(
        "--webhook-url", default=os.environ.get("CANARYTOKENS_WEBHOOK_URL")
    )
    parser.add_argument(
        "--memo",
        default=os.environ.get(
            "CANARYTOKENS_MEMO",
            "DVAP local repository assessment AWS credential",
        ),
    )
    parser.add_argument(
        "--base-url",
        default=os.environ.get("CANARYTOKENS_BASE_URL", DEFAULT_BASE_URL),
    )
    parser.add_argument(
        "--endpoint",
        default=os.environ.get("CANARYTOKENS_GENERATE_ENDPOINT", DEFAULT_ENDPOINT),
    )
    parser.add_argument(
        "--env-output",
        type=Path,
        default=Path("seeds/canarytokens.local.env"),
    )
    parser.add_argument(
        "--metadata-output",
        type=Path,
        default=Path("seeds/canarytokens.local.json"),
    )
    return parser


def _post_form(url: str, values: dict[str, str]) -> dict[str, Any]:
    data = urllib.parse.urlencode(values).encode("utf-8")
    request = urllib.request.Request(
        url,
        data=data,
        headers={
            "Accept": "application/json",
            "Content-Type": "application/x-www-form-urlencoded",
            "User-Agent": "DVAP-Security-Platform/1.0",
        },
        method="POST",
    )
    try:
        with urllib.request.urlopen(request, timeout=30) as response:
            body = response.read().decode("utf-8")
    except urllib.error.HTTPError as exc:
        body = exc.read().decode("utf-8", errors="replace")
        raise RuntimeError(
            f"Canarytokens.org returned HTTP {exc.code}: {body}"
        ) from exc
    except urllib.error.URLError as exc:
        raise RuntimeError(f"Could not reach Canarytokens.org: {exc}") from exc

    try:
        parsed = json.loads(body)
    except json.JSONDecodeError as exc:
        raise RuntimeError(
            f"Canarytokens.org returned non-JSON response: {body}"
        ) from exc
    if not isinstance(parsed, dict):
        raise RuntimeError(f"Canarytokens.org returned unexpected response: {body}")
    return parsed


def _write_outputs(
    payload: dict[str, Any], env_output: Path, metadata_output: Path
) -> tuple[str, str]:
    access_key = str(payload.get("aws_access_key_id") or "")
    secret_key = str(payload.get("aws_secret_access_key") or "")
    if not access_key or not secret_key:
        raise RuntimeError(
            "Canarytokens.org response did not include AWS credential fields"
        )

    env_output.parent.mkdir(parents=True, exist_ok=True)
    metadata_output.parent.mkdir(parents=True, exist_ok=True)

    env_output.write_text(
        "\n".join(
            (
                "# Generated by scripts/create_canarytokens.py via Canarytokens.org.",
                "# Do not commit this file.",
                "DVAP_ALLOW_EXTERNAL_CANARYTOKENS=1",
                f"AWS_CANARY_ACCESS_KEY_ID={access_key}",
                f"AWS_CANARY_SECRET_ACCESS_KEY={secret_key}",
                "",
            )
        ),
        encoding="utf-8",
    )
    metadata_output.write_text(
        json.dumps(payload, indent=2, sort_keys=True) + "\n", encoding="utf-8"
    )
    return access_key, secret_key


def main() -> int:
    args = _arg_parser().parse_args()
    if not args.email:
        print(
            "Set CANARYTOKENS_EMAIL or pass --email so Canarytokens.org has an "
            "alert destination.",
            file=sys.stderr,
        )
        return 2

    base_url = str(args.base_url).rstrip("/")
    endpoint = str(args.endpoint)
    url = f"{base_url}{endpoint if endpoint.startswith('/') else '/' + endpoint}"
    form = {
        "token_type": "aws_keys",
        "email": str(args.email),
        "memo": str(args.memo),
    }
    if args.webhook_url:
        form["webhook_url"] = str(args.webhook_url)

    response = _post_form(url, form)
    error_message = response.get("error_message")
    if error_message:
        raise RuntimeError(str(error_message))

    access_key, _secret_key = _write_outputs(
        response,
        Path(args.env_output),
        Path(args.metadata_output),
    )

    print("Created Canarytokens.org AWS token seed overlay.")
    print(f"  Access key: {access_key}")
    print(f"  Env file:   {args.env_output}")
    print(f"  Metadata:   {args.metadata_output}")
    print("Restart the compose stack for services to load the generated keys.")
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except RuntimeError as exc:
        print(str(exc), file=sys.stderr)
        raise SystemExit(1) from exc
